"""
Application Constants

Centralized constants for document types, categories, and other application-wide values.
"""

DOCUMENT_TYPES = [
    {
        'key': 'bank_statement_dkb',
        'label': 'DKB Bank Statement',
        'category': 'bank',
        'description': 'CSV exports from Deutsche Kreditbank (DKB) Girokonto or Tagesgeld accounts.',
        'extensions': ['.csv'],
        'parser': 'parse_dkb',
        'sample_data_path': 'data/bank_statements/dkb'
    },
    {
        'key': 'bank_statement_yuh',
        'label': 'YUH Activity Export',
        'category': 'bank',
        'description': 'Activity exports from the YUH app stored as CSV files.',
        'extensions': ['.csv'],
        'parser': 'parse_yuh',
        'sample_data_path': 'data/bank_statements/yuh'
    },
    {
        'key': 'broker_viac_pdf',
        'label': 'VIAC Trade Confirmation',
        'category': 'broker',
        'description': 'Trade confirmation PDFs generated by VIAC.',
        'extensions': ['.pdf'],
        'parser': 'parse_viac',
        'sample_data_path': 'data/depot_transactions/viac'
    },
    {
        'key': 'broker_ing_diba_csv',
        'label': 'ING DiBa Depot Overview',
        'category': 'broker',
        'description': 'Depot overview CSV exports from ING DiBa.',
        'extensions': ['.csv'],
        'parser': 'parse_ing_diba',
        'sample_data_path': 'data/depot_transactions/ing_diba'
    },
    {
        'key': 'loan_kfw_pdf',
        'label': 'KfW Loan Statement',
        'category': 'loan',
        'description': 'KfW student loan account statements as PDF files.',
        'extensions': ['.pdf'],
        'parser': 'parse_kfw',
        'sample_data_path': 'data/credits/kfw'
    }
]

DOCUMENT_TYPE_LOOKUP = {doc['key']: doc for doc in DOCUMENT_TYPES}

