#!/usr/bin/env python3
"""Generate AGENTS.md, Claude/Cursor rules, and Codex nested AGENTS.md from docs/agents/."""

from __future__ import annotations

import os
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "agents"
CORE = DOCS / "core"
RULES = DOCS / "rules"
SKILLS = DOCS / "skills"

ALLOWED_RULE_KEYS = {"description", "alwaysApply", "paths", "codexTarget", "body"}
GENERATED_MARKER = "<!-- generated by scripts/sync-agent-docs.sh"
CODEX_TARGETS = ("backend", "frontend")
SKILL_SYMLINKS = (
    ROOT / ".agents" / "skills",
    ROOT / ".claude" / "skills",
    ROOT / ".cursor" / "skills",
)


def parse_rule_yaml(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if "body: |" not in text:
        raise ValueError(f"{path}: expected 'body: |' block")
    header, body = text.split("body: |", 1)
    body = textwrap.dedent(body.lstrip("\n")).rstrip()

    rule: dict = {"body": body}
    in_paths = False
    for line in header.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            in_paths = False
            continue
        if line.startswith("description:"):
            in_paths = False
            rule["description"] = line.split(":", 1)[1].strip()
        elif line.startswith("alwaysApply:"):
            in_paths = False
            rule["alwaysApply"] = line.split(":", 1)[1].strip().lower() == "true"
        elif line.startswith("codexTarget:"):
            in_paths = False
            val = line.split(":", 1)[1].strip()
            rule["codexTarget"] = None if val in ("null", "", "~") else val
        elif line.startswith("paths:"):
            in_paths = True
            rule["paths"] = []
        elif line.startswith("- ") and in_paths:
            rule.setdefault("paths", []).append(line[2:].strip())
        else:
            raise ValueError(f"{path}: unrecognized header line: {line!r}")

    unknown = set(rule) - ALLOWED_RULE_KEYS
    if unknown:
        raise ValueError(f"{path}: unknown keys {unknown}")
    for key in ("description", "alwaysApply", "body"):
        if key not in rule:
            raise ValueError(f"{path}: missing required key '{key}'")
    rule.setdefault("paths", [])
    rule.setdefault("codexTarget", None)
    return rule


def assemble_agents_md(rules: list[tuple[str, dict]]) -> str:
    parts = [f"{GENERATED_MARKER}; edit docs/agents/ -->\n"]
    for core_file in sorted(CORE.glob("*.md")):
        parts.append(core_file.read_text(encoding="utf-8").rstrip())
        parts.append("\n\n")

    always_on = [rule for _, rule in rules if rule["alwaysApply"]]
    if always_on:
        parts.append("## Enforced rules\n\n")
        for rule in always_on:
            parts.append(rule["body"])
            parts.append("\n\n")

    return "".join(parts).rstrip() + "\n"


def claude_rule_content(rule: dict) -> str:
    lines = ["---"]
    if rule["paths"]:
        lines.append("paths:")
        for path in rule["paths"]:
            lines.append(f"  - {path}")
    lines.extend(["---", "", rule["body"]])
    return "\n".join(lines) + "\n"


def cursor_rule_content(rule: dict) -> str:
    lines = [
        "---",
        f"description: {rule['description']}",
        f"alwaysApply: {'true' if rule['alwaysApply'] else 'false'}",
    ]
    if rule["paths"]:
        lines.append(f"globs: {', '.join(rule['paths'])}")
    lines.extend(["---", "", rule["body"]])
    return "\n".join(lines) + "\n"


def codex_agents_md(target: str, rules: list[tuple[str, dict]]) -> str | None:
    bodies = [
        rule["body"]
        for _, rule in rules
        if not rule["alwaysApply"] and rule.get("codexTarget") == target
    ]
    if not bodies:
        return None
    header = f"{GENERATED_MARKER}; edit docs/agents/rules/ -->\n\n"
    return header + "\n\n".join(bodies) + "\n"


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def ensure_symlink(link: Path, target: Path) -> None:
    target_rel = os.path.relpath(target, link.parent)
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.is_symlink() and os.readlink(link) == target_rel:
        return
    if link.exists() or link.is_symlink():
        link.unlink()
    link.symlink_to(target_rel)


def sync_rule_outputs(rules: list[tuple[str, dict]]) -> None:
    claude_dir = ROOT / ".claude" / "rules"
    cursor_dir = ROOT / ".cursor" / "rules"
    claude_dir.mkdir(parents=True, exist_ok=True)
    cursor_dir.mkdir(parents=True, exist_ok=True)

    expected_claude = {f"{name}.md" for name, _ in rules}
    expected_cursor = {f"{name}.mdc" for name, _ in rules}

    for name, rule in rules:
        write_if_changed(claude_dir / f"{name}.md", claude_rule_content(rule))
        write_if_changed(cursor_dir / f"{name}.mdc", cursor_rule_content(rule))

    for directory, expected in (
        (claude_dir, expected_claude),
        (cursor_dir, expected_cursor),
    ):
        for path in directory.iterdir():
            if path.is_file() and path.name not in expected:
                path.unlink()


def sync_codex_agents(rules: list[tuple[str, dict]]) -> None:
    for target in CODEX_TARGETS:
        content = codex_agents_md(target, rules)
        path = ROOT / target / "AGENTS.md"
        if content:
            write_if_changed(path, content)
        elif path.exists() and path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            path.unlink()


def main() -> int:
    if not DOCS.is_dir():
        print(f"Missing {DOCS}", file=sys.stderr)
        return 1

    rules = [(path.stem, parse_rule_yaml(path)) for path in sorted(RULES.glob("*.yaml"))]

    write_if_changed(ROOT / "AGENTS.md", assemble_agents_md(rules))
    sync_rule_outputs(rules)
    sync_codex_agents(rules)

    ensure_symlink(ROOT / "CLAUDE.md", ROOT / "AGENTS.md")
    for link in SKILL_SYMLINKS:
        ensure_symlink(link, SKILLS)

    print("Synced agent docs from docs/agents/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
